#!/bin/bash

# Source tutorial run functions
source $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`
runApplication blockMesh
# Run
runApplication $application

postProcess -func flux



#------------------------------------------------------------------------------
